import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Github Profile Search</title>
        <link rel="shortcut icon" href="/favicon.ico" />
        <meta charSet='UTF-8'></meta>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
